### ISSUE TITLE
一个typo

### ISSUE THREAD

**Issue by chatouis** [SkiperDyxx/USTC_AlgorithmForBigData2023#2]
助教你好。Morris++ 算法的分析中估计的概率 $P(\tilde{n} \ \text{is\ bad})$ 在笔记中打成 $\mathbb{P}[|\tilde{n}-n| \leq \epsilon n]$  了。

**Comment by xyxu2033** [comment]
谢谢提醒，已经更正了，同时对这边增加了更多的解释
